version: '3.9'

services:
  node:
    container_name: iloveimages
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - AWS_REGION=sa-east-1
      - AWS_BUCKET_NAME=iloveimages-bucket
      - AWS_CLOUDFRONT_URL=https://d15gw9m6f1r81r.cloudfront.net/
      - CACHE_DB_HOST=redis
      - CACHE_DB_PORT=6379
      - CACHE_TTL=86400
      - ENVIROMENT=DEVELOPMENT
      - VERSION=1.0.0
    depends_on:
      - redis
    networks:
      - iloveimages-network

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - iloveimages-network

networks:
  iloveimages-network:
   driver: bridge