version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
