import Contexts from "@/contexts";
import { NextUIProvider } from "@nextui-org/system";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "ILoveImages",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <Contexts>
            <div className="app-theme bg-background text-foreground">
              <ToastContainer />

              {children}
            </div>
          </Contexts>
        </NextUIProvider>
      </body>
    </html>
  );
}
