export enum EnvVariablesEnum {
  ACCESS_KEY_ID = 'ACCESS_KEY_ID',
  ACCESS_KEY_SECRET = 'ACCESS_KEY_SECRET',
  AWS_REGION = 'AWS_REGION',
  AWS_BUCKET_NAME = 'AWS_BUCKET_NAME',
  CACHE_DB_HOST = 'CACHE_DB_HOST',
  CACHE_DB_PORT = 'CACHE_DB_PORT',
  CACHE_TTL = 'CACHE_TTL',
  ENVIROMENT = 'ENVIROMENT',
  VERSION = 'VERSION',
}
