export enum EnvVariablesEnum {
  ACCESS_KEY_ID = 'ACCESS_KEY_ID',
  ACCESS_KEY_SECRET = 'ACCESS_KEY_SECRET',
  AWS_REGION = 'AWS_REGION',
  AWS_BUCKET_NAME = 'AWS_BUCKET_NAME',
  ENVIROMENT = 'ENVIROMENT',
  VERSION = 'VERSION',
}
